// Contains all the Action types used in App.
export const SHOW_RETRY_UI = "SHOW_RETRY_UI";
export const DELETE_RETRY_UI = "DELETE_RETRY_UI";

//landing screen
export const LOADING = "LOADING";
export const ACTIVATION_STATUS = "ACTIVATION_STATUS";
export const ERROR = "ERROR";



//
export const GET_LIST_DATA_LOADING = "GET_LIST_DATA_LOADING";
export const GET_LIST_DATA_SUCCESS = "GET_LIST_DATA_SUCCESS";
export const GET_LIST_DATA_FAILURE = "GET_LIST_DATA_FAILURE";
export const GET_LIST_DATA_CLEAR = "GET_LIST_DATA_LEAR";


//GET_LIST_DATA_MORE
export const GET_LIST_DATA_MORE_LOADING = "GET_LIST_DATA_MORE_LOADING";
export const GET_LIST_DATA_MORE_SUCCESS = "GET_LIST_DATA_MORE_SUCCESS";
export const GET_LIST_DATA_MORE_FAILURE = "GET_LIST_DATA_MORE_FAILURE";
export const GET_LIST_DATA_MORE_CLEAR = "GET_LIST_DATA_MORE_LEAR";